Elasticsearch indexation
Ferlab-Ste-Justine/clin-fhir-server pull request #8
Opened 2020-09-30 15:56 UTC by YanLabCHU

2020-09-30 16:07 UTC, jecos requested changes

2020-09-30 16:07 UTC, jecos commented on src/main/java/bio/ferlab/clin/es/data/UpdateResponseListener.java
> +        } catch (Exception e) {
This exception is silently caught

2020-09-30 16:07 UTC, jecos commented on src/main/java/bio/ferlab/clin/es/data/ElasticsearchData.java
> +        } catch (IOException e) {
This exception is silently caught

2020-09-30 16:14 UTC, plaplante-chust commented on src/main/java/bio/ferlab/clin/es/data/ElasticResponse.java
> +        @JsonProperty("_index")
That's a personal preference but, I usually put the annotations on the field and use lombok for the getters/setters/constructors/hashcode/equals  etc.

2020-09-30 16:18 UTC, plaplante-chust commented on src/main/java/bio/ferlab/clin/interceptors/IndexerInterceptor.java
> +        // Autowired doesn't work, so we need the ApplicationContext to get the bean.
Did you try to implement ApplicationContextAware or use @Inject instead?

2020-09-30 16:22 UTC, plaplante-chust commented on src/main/java/bio/ferlab/clin/interceptors/IndexerInterceptor.java
> +        // Autowired doesn't work, so we need the ApplicationContext to get the bean.
Did you try implementing ApplicationContextAware?

2020-09-30 16:23 UTC, plaplante-chust commented on src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
> +        return HapiProperties.getIntegerProperty(BIO_ES_TRANSPORT_PORT, 9201);
Isn't the default transport port usually 9300?

2020-09-30 16:24 UTC, plaplante-chust commented on src/test/java/bio/ferlab/clin/es/ElasticsearchRestClientTest.java
> +public class ElasticsearchRestClientTest {
:+1:

2020-09-30 16:57 UTC, YanLabCHU commented on src/main/java/bio/ferlab/clin/interceptors/IndexerInterceptor.java
> +        // Autowired doesn't work, so we need the ApplicationContext to get the bean.
Yes, I tried it and it didn't work

2020-10-01 13:38 UTC, plaplante-chust approved these changes

2020-10-01 13:41 UTC, merged